# Generated by Django 5.2.10 on 2026-01-11 06:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Food item name', max_length=100, unique=True)),
                ('calories_per_unit', models.IntegerField(help_text='Calories per standard unit of this food')),
                ('default_unit', models.CharField(choices=[('piece', 'Piece(s)'), ('gram', 'Gram(s)'), ('kg', 'Kilogram(s)'), ('ml', 'Milliliter(s)'), ('liter', 'Liter(s)'), ('cup', 'Cup(s)'), ('tablespoon', 'Tablespoon(s)'), ('teaspoon', 'Teaspoon(s)'), ('bowl', 'Bowl(s)'), ('serving', 'Serving(s)')], help_text='Default unit for this food', max_length=20)),
                ('protein_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Protein per unit (grams)', max_digits=6, null=True)),
                ('carbs_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Carbohydrates per unit (grams)', max_digits=6, null=True)),
                ('fat_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Fat per unit (grams)', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this meal plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=20)),
                ('food_name', models.CharField(help_text='Food item name (legacy)', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity amount', max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('quantity_unit', models.CharField(choices=[('piece', 'Piece(s)'), ('gram', 'Gram(s)'), ('kg', 'Kilogram(s)'), ('ml', 'Milliliter(s)'), ('liter', 'Liter(s)'), ('cup', 'Cup(s)'), ('tablespoon', 'Tablespoon(s)'), ('teaspoon', 'Teaspoon(s)'), ('bowl', 'Bowl(s)'), ('serving', 'Serving(s)')], max_length=20)),
                ('calories', models.IntegerField(blank=True, help_text='Calculated calories', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this food item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(help_text='Food item', on_delete=django.db.models.deletion.CASCADE, to='planning.food')),
                ('meal_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='planning.mealday')),
            ],
            options={
                'ordering': ['meal_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lose', 'Weight Loss'), ('maintain', 'Maintain Weight'), ('gain', 'Weight Gain')], max_length=20)),
                ('daily_calorie_target', models.IntegerField(help_text='Target daily calories for this goal')),
                ('tolerance_calories', models.IntegerField(default=100, help_text='Acceptable variance from target')),
                ('start_date', models.DateField(help_text='When this goal starts')),
                ('end_date', models.DateField(blank=True, help_text='When this goal ends (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this goal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wake_up_offset', models.IntegerField(default=0, help_text='Minutes from wake up time')),
                ('water_offset', models.IntegerField(default=5, help_text='Minutes from wake up time')),
                ('walk_offset', models.IntegerField(default=15, help_text='Minutes from wake up time')),
                ('breakfast_offset', models.IntegerField(default=180, help_text='Minutes from wake up time')),
                ('lunch_offset', models.IntegerField(default=420, help_text='Minutes from wake up time')),
                ('snacks_offset', models.IntegerField(default=600, help_text='Minutes from wake up time')),
                ('dinner_offset', models.IntegerField(default=840, help_text='Minutes from wake up time')),
                ('sleep_reminder_offset', models.IntegerField(default=960, help_text='Minutes from wake up time')),
                ('water_amount_ml', models.IntegerField(default=300, help_text='Water amount in ml')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this timeline')),
                ('activity_type', models.CharField(choices=[('wake_up', 'Wake Up'), ('water', 'Water'), ('walk', 'Walk'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner'), ('sleep_reminder', 'Sleep Reminder')], max_length=20)),
                ('activity_name', models.CharField(max_length=100)),
                ('scheduled_time', models.TimeField(help_text='Scheduled time for this activity')),
                ('offset_minutes', models.IntegerField(help_text='Minutes offset from wake up time')),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'scheduled_time'],
                'unique_together': {('user', 'date', 'activity_type')},
            },
        ),
    ]
