# Generated by Django 5.2.10 on 2026-01-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Food item name', max_length=100, unique=True)),
                ('calories_per_unit', models.IntegerField(help_text='Calories per standard unit of this food')),
                ('default_unit', models.CharField(choices=[('piece', 'Piece(s)'), ('gram', 'Gram(s)'), ('kg', 'Kilogram(s)'), ('ml', 'Milliliter(s)'), ('liter', 'Liter(s)'), ('cup', 'Cup(s)'), ('tablespoon', 'Tablespoon(s)'), ('teaspoon', 'Teaspoon(s)'), ('bowl', 'Bowl(s)'), ('serving', 'Serving(s)')], help_text='Default unit for this food', max_length=20)),
                ('protein_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Protein per unit (grams)', max_digits=6, null=True)),
                ('carbs_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Carbohydrates per unit (grams)', max_digits=6, null=True)),
                ('fat_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Fat per unit (grams)', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
