# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_target_liters', models.DecimalField(choices=[(2.0, '2 Liters'), (2.5, '2.5 Liters'), (3.0, '3 Liters')], decimal_places=1, help_text='Daily water intake target in liters', max_digits=3)),
                ('start_date', models.DateField(help_text='When this goal starts')),
                ('end_date', models.DateField(blank=True, help_text='When this goal ends (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this schedule')),
                ('wake_up_time', models.TimeField(help_text="User's wake up time for this day")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_schedules', to=settings.AUTH_USER_MODEL)),
                ('water_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='water.watergoal')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WaterTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField(help_text='Scheduled time for water intake')),
                ('amount_ml', models.IntegerField(help_text='Amount of water in milliliters', validators=[MinValueValidator(50), MaxValueValidator(1000)])),
                ('is_meal_restricted', models.BooleanField(default=False, help_text='Whether this slot avoids meal times')),
                ('meal_type', models.CharField(blank=True, help_text='Associated meal type if restricted', max_length=20)),
                ('is_consumed', models.BooleanField(default=False)),
                ('consumed_amount_ml', models.IntegerField(blank=True, help_text='Actual amount consumed in ml', null=True, validators=[MinValueValidator(0)])),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='water.waterschedule')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]